// <auto-generated />
using System;
using CRM.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.API.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CRM.API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "TechCorp",
                            CreatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(5911),
                            Email = "alice@techcorp.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "+1-555-0101",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(5913)
                        },
                        new
                        {
                            Id = 2,
                            Company = "Acme Inc",
                            CreatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(5921),
                            Email = "bob@acme.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            Phone = "+1-555-0102",
                            Status = "Lead",
                            UpdatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(5922)
                        },
                        new
                        {
                            Id = 3,
                            Company = "Global Ent",
                            CreatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(5929),
                            Email = "carol@globalent.com",
                            FirstName = "Carol",
                            LastName = "White",
                            Phone = "+1-555-0103",
                            Status = "Prospect",
                            UpdatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(5931)
                        });
                });

            modelBuilder.Entity("CRM.API.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpectedCloseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Probability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Deals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6381),
                            CustomerId = 1,
                            ExpectedCloseDate = new DateTime(2026, 7, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6363),
                            Probability = 60,
                            Stage = "Proposal",
                            Title = "Enterprise License",
                            UpdatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6382),
                            Value = 50000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6394),
                            CustomerId = 2,
                            ExpectedCloseDate = new DateTime(2026, 8, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6391),
                            Probability = 40,
                            Stage = "Qualification",
                            Title = "Starter Package",
                            UpdatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6395),
                            Value = 5000m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6411),
                            CustomerId = 3,
                            ExpectedCloseDate = new DateTime(2026, 7, 11, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6402),
                            Probability = 80,
                            Stage = "Negotiation",
                            Title = "Premium Support",
                            UpdatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6413),
                            Value = 12000m
                        });
                });

            modelBuilder.Entity("CRM.API.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6532),
                            CustomerId = 1,
                            DueDate = new DateTime(2026, 6, 28, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6529),
                            Priority = "High",
                            Status = "Pending",
                            Title = "Follow up on proposal",
                            UpdatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6534)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6543),
                            CustomerId = 2,
                            DueDate = new DateTime(2026, 7, 1, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6541),
                            Priority = "Medium",
                            Status = "In Progress",
                            Title = "Schedule demo call",
                            UpdatedAt = new DateTime(2026, 6, 26, 8, 46, 58, 481, DateTimeKind.Utc).AddTicks(6544)
                        });
                });

            modelBuilder.Entity("CRM.API.Models.Deal", b =>
                {
                    b.HasOne("CRM.API.Models.Customer", "Customer")
                        .WithMany("Deals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM.API.Models.TaskItem", b =>
                {
                    b.HasOne("CRM.API.Models.Customer", "Customer")
                        .WithMany("Tasks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM.API.Models.Customer", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
